#!/usr/bin/env python3
"""Generate testdata/protocol-vectors.json (PROTOCOL.md §2.1). Stdlib only.

Run: python3 -I testdata/gen_protocol_vectors.py > testdata/protocol-vectors.json
"""
import base64
import hashlib
import hmac
import json
import struct

MAX_FRAME_LEN = 1_048_592
MAX_CHUNK = 262_144
PREFACE = b"IOST\x01\x00\x00\x00"


CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def pairing_code(pin: bytes) -> str:
    """PROTOCOL §4.1: first 40 bits of the SPKI pin, Crockford base32, MSB first, as XXXX-XXXX."""
    v = int.from_bytes(pin[:5], "big")
    chars = "".join(CROCKFORD[(v >> (35 - 5 * i)) & 31] for i in range(8))
    return chars[:4] + "-" + chars[4:]


def frame(ty: int, payload: bytes) -> bytes:
    return struct.pack(">IB", 1 + len(payload), ty) + payload


def data_payload(slot: int, offset: int, data: bytes) -> bytes:
    return struct.pack(">HQ", slot, offset) + data


def control(name, ty, text):
    payload = text.encode("utf-8")
    return {
        "name": name,
        "type": ty,
        "kind": "control",
        "json_text": text,
        "hex": frame(ty, payload).hex(),
    }


def data(name, slot, offset, data_bytes):
    return {
        "name": name,
        "type": 0x21,
        "kind": "data",
        "slot": slot,
        "offset": offset,
        "bytes_hex": data_bytes.hex(),
        "hex": frame(0x21, data_payload(slot, offset, data_bytes)).hex(),
    }


def main():
    out = {
        "about": "IOStransfer protocol v1 test vectors (docs/PROTOCOL.md). Generated by "
        "testdata/gen_protocol_vectors.py; do not edit by hand.",
        "constants": {"max_frame_len": MAX_FRAME_LEN, "max_chunk": MAX_CHUNK, "preface_hex": PREFACE.hex()},
        "notes": [
            "frames[].hex is exact for the header and for DATA. For control frames, implementations MUST decode "
            "hex to the same (type, JSON value); their own encoder may order keys or space differently, so encode "
            "tests compare decode(encode(x)) == x and parse(json_text) == x, not bytes.",
            "decode_errors[] feed `input` (hex, or a `gen` spec) to a fresh decoder in one buffer. "
            "`stage` says which layer must reject it: preface | frame (codec) | data (DATA payload parse) | "
            "message (JSON parse of a known control type). `expect` is ok | need_more | bad_preface | "
            "bad_length | unknown_type | bad_data | bad_json.",
            "gen spec: {\"header_len\": L, \"type\": T, \"payload_fill\": \"00\", \"payload_len\": N} builds "
            "u32 BE L | u8 T | N bytes of fill; DATA gens add slot/offset as the first 10 payload bytes.",
        ],
    }

    frames = [
        control("ping_n1", 0x70, '{"n":1}'),
        control("pong_n1", 0x71, '{"n":1}'),
        control("paired_empty", 0x05, "{}"),
        control("resume_empty", 0x51, "{}"),
        control("bye_done", 0x7F, '{"code":"done"}'),
        control("log_utf8", 0x60, '{"lvl":"i","ts_ms":1710411322000,"msg":"héllo \U0001F4F7"}'),
        control(
            "hello_secret",
            0x01,
            '{"proto":{"min":1,"max":1},"device_id":"0b7c1c1e-3f7a-4c8e-9a51-2a3b4c5d6e7f",'
            '"device_name":"Test iPhone","app_version":"0.1.0","os":"iOS 19.1",'
            '"auth":{"mode":"secret","s_nonce":"' + "02" * 32 + '"}}',
        ),
        control(
            "res_begin",
            0x20,
            '{"slot":0,"id":"6F3A0000-0000-0000-0000-000000000001/L0/001","key":"photo#0","offset":0,"size":3}',
        ),
        control("res_end_abc", 0x22, '{"slot":0,"size":3,"sha256":"' + hashlib.sha256(b"abc").hexdigest() + '"}'),
        data("data_slot1_off0_abc", 1, 0, b"abc"),
        data("data_slot65535_off_2p40", 0xFFFF, 1 << 40, b"\x00\xff"),
    ]
    out["frames"] = frames

    out["streams"] = [
        {
            "name": "two_pings_one_buffer",
            "hex": (frame(0x70, b'{"n":1}') + frame(0x70, b'{"n":2}')).hex(),
            "expect_types": [0x70, 0x70],
        },
        {
            "name": "preface_then_ping_bytewise",
            "note": "after the preface, a decoder fed byte-by-byte must yield exactly one PING",
            "hex": (PREFACE + frame(0x70, b'{"n":7}')).hex(),
            "expect_types": [0x70],
        },
    ]

    big_ok = {"header_len": 1 + 10 + MAX_CHUNK, "type": 0x21, "slot": 0, "offset": 0,
              "payload_fill": "00", "payload_len": MAX_CHUNK}
    big_bad = dict(big_ok, header_len=1 + 10 + MAX_CHUNK + 1, payload_len=MAX_CHUNK + 1)
    max_len_ok = {"header_len": MAX_FRAME_LEN, "type": 0x60, "payload_fill": "20",
                  "payload_len": MAX_FRAME_LEN - 1}
    out["decode_errors"] = [
        {"name": "empty", "stage": "frame", "input": "", "expect": "need_more"},
        {"name": "header_3_bytes", "stage": "frame", "input": "000000", "expect": "need_more"},
        {"name": "header_only", "stage": "frame", "input": "00000008", "expect": "need_more"},
        {"name": "payload_truncated", "stage": "frame", "input": frame(0x70, b'{"n":1}')[:-1].hex(),
         "expect": "need_more"},
        {"name": "len_zero", "stage": "frame", "input": "00000000", "expect": "bad_length"},
        {"name": "len_max_plus_1_header_only", "stage": "frame",
         "note": "MUST fail from the 4 header bytes alone, before buffering any payload",
         "input": struct.pack(">I", MAX_FRAME_LEN + 1).hex(), "expect": "bad_length"},
        {"name": "len_u32_max", "stage": "frame", "input": "ffffffff", "expect": "bad_length"},
        {"name": "len_exactly_max", "stage": "frame", "gen": max_len_ok, "expect": "ok"},
        {"name": "unknown_type_0x06", "stage": "frame", "input": frame(0x06, b"{}").hex(), "expect": "unknown_type"},
        {"name": "unknown_type_0x00", "stage": "frame", "input": frame(0x00, b"{}").hex(), "expect": "unknown_type"},
        {"name": "unknown_type_0xff", "stage": "frame", "input": frame(0xFF, b"{}").hex(), "expect": "unknown_type"},
        {"name": "data_payload_10_bytes_no_chunk", "stage": "data",
         "input": frame(0x21, data_payload(0, 0, b"")).hex(), "expect": "bad_data"},
        {"name": "data_payload_2_bytes", "stage": "data", "input": frame(0x21, b"\x00\x01").hex(),
         "expect": "bad_data"},
        {"name": "data_chunk_exactly_max", "stage": "data", "gen": big_ok, "expect": "ok"},
        {"name": "data_chunk_max_plus_1", "stage": "data", "gen": big_bad, "expect": "bad_data"},
        {"name": "control_bad_json", "stage": "message", "input": frame(0x70, b'{"n":').hex(),
         "expect": "bad_json"},
        {"name": "control_not_object", "stage": "message", "input": frame(0x70, b"[1]").hex(),
         "expect": "bad_json"},
        {"name": "control_bom", "stage": "message", "input": frame(0x70, b'\xef\xbb\xbf{"n":1}').hex(),
         "expect": "bad_json"},
        {"name": "control_invalid_utf8", "stage": "message", "input": frame(0x60, b'{"msg":"\xff"}').hex(),
         "expect": "bad_json"},
        {"name": "control_unknown_field_ok", "stage": "message", "input": frame(0x70, b'{"n":1,"zz":true}').hex(),
         "expect": "ok"},
        {"name": "preface_ok", "stage": "preface", "input": PREFACE.hex(), "expect": "ok"},
        {"name": "preface_short", "stage": "preface", "input": PREFACE[:5].hex(), "expect": "need_more"},
        {"name": "preface_version_2", "stage": "preface", "input": b"IOST\x02\x00\x00\x00".hex(),
         "expect": "bad_preface"},
        {"name": "preface_reserved_nonzero", "stage": "preface", "input": b"IOST\x01\x00\x00\x01".hex(),
         "expect": "bad_preface"},
        {"name": "preface_http", "stage": "preface", "input": b"GET / HT".hex(), "expect": "bad_preface"},
        {"name": "preface_tls_clienthello", "stage": "preface",
         "note": "a TLS client hitting a plain (USB) listener", "input": "160301020001000001fc0303",
         "expect": "bad_preface"},
    ]

    secret, s_nonce, r_nonce = bytes([1]) * 32, bytes([2]) * 32, bytes([3]) * 32
    out["hmac"] = [{
        "secret": secret.hex(), "s_nonce": s_nonce.hex(), "r_nonce": r_nonce.hex(),
        "r_proof": hmac.new(secret, b"IOST1-R" + s_nonce + r_nonce, hashlib.sha256).hexdigest(),
        "s_proof": hmac.new(secret, b"IOST1-S" + s_nonce + r_nonce, hashlib.sha256).hexdigest(),
    }]

    prefix = bytes.fromhex("3059301306072a8648ce3d020106082a8648ce3d030107034200")
    point = bytes.fromhex(
        "04263f76ef1090bca655dcf3720aef96a5e0169539c7a233f2b91ff18c2889d03a"
        "6e47dd37ab6435993d2559afb04ddab2f8b8af3a7adee4535c2c33853f2c535b")
    der = prefix + point
    pin = hashlib.sha256(der).digest()
    out["spki"] = [{
        "key_type": "ecdsa_p256",
        "point_hex": point.hex(),
        "spki_der_hex": der.hex(),
        "pin_sha256_hex": pin.hex(),
        "pin_b64url_nopad": base64.urlsafe_b64encode(pin).rstrip(b"=").decode(),
        "pairing_code": pairing_code(pin),
    }]
    out["pairing_code"] = [
        {"pin_sha256_hex": h.hex(), "code": pairing_code(h)}
        for h in (pin, bytes(32), bytes([0xFF]) * 32, bytes.fromhex("0123456789") + bytes(27))
    ]

    def fp(meta, res):
        lat = "-" if meta.get("loc") is None else "%.7f" % meta["loc"]["lat"]
        lon = "-" if meta.get("loc") is None else "%.7f" % meta["loc"]["lon"]
        alt = "-" if meta.get("loc") is None or meta["loc"].get("alt") is None else "%.2f" % meta["loc"]["alt"]
        s = "meta\t%d\t%s\t%s\t%s\t%s\n" % (meta["created_ms"], "1" if meta["fav"] else "0", lat, lon, alt)
        for r in sorted(res, key=lambda r: r["key"].encode()):
            h = r["sha256"] if r["key"].startswith("adjustment_data#") else "-"
            s += "%s\t%d\t%s\n" % (r["key"], r["size"], h)
        return s, hashlib.sha256(s.encode()).hexdigest()

    aae = hashlib.sha256(b"<plist/>").hexdigest()
    fp_cases = [
        ("live_photo_no_loc", {"created_ms": 1710411322000, "fav": False},
         [{"key": "photo#0", "size": 2481234}, {"key": "paired_video#0", "size": 3011122}]),
        ("edited_with_loc", {"created_ms": 1710411322000, "fav": True,
                             "loc": {"lat": 48.85837009999, "lon": 2.2944813, "alt": 35.2}},
         [{"key": "photo#0", "size": 2481234}, {"key": "full_size_photo#0", "size": 2390001},
          {"key": "adjustment_data#0", "size": 812, "sha256": aae}]),
        ("loc_without_alt", {"created_ms": 0, "fav": False, "loc": {"lat": -33.8567844, "lon": 151.213108}},
         [{"key": "video#0", "size": 1}]),
    ]
    out["fingerprint"] = []
    for name, meta, res in fp_cases:
        canon, h = fp(meta, res)
        out["fingerprint"].append({"name": name, "meta": meta, "res": res, "canonical": canon, "fp": h})

    print(json.dumps(out, indent=1, ensure_ascii=False))


if __name__ == "__main__":
    main()
